version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: project_generator_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project_generator_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d project_generator_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
      
volumes:
  pgdata:
